[book]
authors = ["Arvid SÃ¶rfeldt"]
language = "en"
multilingual = false
src = "src"
title = "SJO747 - Wave Loads and Seakeeping"

[preprocessor.katex]
after = ["links"]

[build]
create-missing = false

[output.html]
git-repository-url = "https://github.com/arvidsorfeldt/seakeeping-manuvering"